logging:
  level:
    org.springframework.security: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  # .env import
  config:
    import: optional:file:./.env[.properties]

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}